### ISSUE TITLE
plugin not working

### ISSUE THREAD

**Issue by lowitea** [best-doctor/flake8-class-attributes-order#3]
```
─$ flake8 backend                                                                                                                                  1 ↵
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/lowit/.local/share/virtualenvs/filmover--nVAlw3n/lib/python3.6/site-packages/flake8/checker.py", line 669, in _run_checks
    return checker.run_checks()
  File "/home/lowit/.local/share/virtualenvs/filmover--nVAlw3n/lib/python3.6/site-packages/flake8/checker.py", line 608, in run_checks
    self.run_ast_checks()
  File "/home/lowit/.local/share/virtualenvs/filmover--nVAlw3n/lib/python3.6/site-packages/flake8/checker.py", line 504, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/home/lowit/.local/share/virtualenvs/filmover--nVAlw3n/lib/python3.6/site-packages/flake8_class_attributes_order/checker.py", line 206, in run
    model_parts_info = self._get_model_parts_info(class_def, weight_info)
  File "/home/lowit/.local/share/virtualenvs/filmover--nVAlw3n/lib/python3.6/site-packages/flake8_class_attributes_order/checker.py", line 127, in _get_model_parts_info
    'weight': weights[node_type],
KeyError: None
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lowit/.local/share/virtualenvs/filmover--nVAlw3n/bin/flake8", line 10, in <module>
    sys.exit(main())
  File "/home/lowit/.local/share/virtualenvs/filmover--nVAlw3n/lib/python3.6/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/home/lowit/.local/share/virtualenvs/filmover--nVAlw3n/lib/python3.6/site-packages/flake8/main/application.py", line 394, in run
    self._run(argv)
  File "/home/lowit/.local/share/virtualenvs/filmover--nVAlw3n/lib/python3.6/site-packages/flake8/main/application.py", line 382, in _run
    self.run_checks()
  File "/home/lowit/.local/share/virtualenvs/filmover--nVAlw3n/lib/python3.6/site-packages/flake8/main/application.py", line 301, in run_checks
    self.file_checker_manager.run()
  File "/home/lowit/.local/share/virtualenvs/filmover--nVAlw3n/lib/python3.6/site-packages/flake8/checker.py", line 328, in run
    self.run_parallel()
  File "/home/lowit/.local/share/virtualenvs/filmover--nVAlw3n/lib/python3.6/site-packages/flake8/checker.py", line 292, in run_parallel
    for ret in pool_map:
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 347, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
KeyError: None

```

Python 3.6.8
flake8 3.7.7

**Comment by Melevir** [comment]
Could you please provide code, that breaks the plugin?

**Comment by lowitea** [comment]
The problem is this class.
https://gitlab.com/lowit/filmover/blob/master/backend/views/common.py#L41

**Comment by Melevir** [comment]
Fixed. Please, upgrade plugin to version `0.0.3`.
