### ISSUE TITLE
AttributeError: 'Tuple' object has no attribute 'attr'

### ISSUE THREAD

**Issue by Stafil0** [best-doctor/flake8-class-attributes-order#7]
Hi.
This code:
```python
class Foo:
    bar()
    var1, var2 = foobar()
```
Throws:
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8\__main__.py", line 4, in <module>
    cli.main()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8\main\cli.py", line 18, in main
    app.run(argv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8\main\application.py", line 393, in run
    self._run(argv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8\main\application.py", line 381, in _run
    self.run_checks()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8\main\application.py", line 300, in run_checks
    self.file_checker_manager.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8\checker.py", line 331, in run
    self.run_serial()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8\checker.py", line 315, in run_serial
    checker.run_checks()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8\checker.py", line 598, in run_checks
    self.run_ast_checks()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8\checker.py", line 502, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8_class_attributes_order\checker.py", line 215, in run
    errors += self._get_ordering_errors(model_parts_info)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8_class_attributes_order\checker.py", line 190, in _get_ordering_errors
    cls._get_node_name(next_model_part['node'], next_model_part['type']),
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8_class_attributes_order\checker.py", line 107, in _get_node_name
    return name_getter(node)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flake8_class_attributes_order\checker.py", line 96, in <lambda>
    n.targets[0].id if isinstance(n.targets[0], ast.Name) else n.targets[0].attr
AttributeError: 'Tuple' object has no attribute 'attr'
```
That might be a bad code styling, but it not supposed to throw exception.

**Comment by Melevir** [comment]
Fixed and released, please upgrade to 0.0.6.
But be careful: flake8-class-attributes-order dropped support of python 3.6, it supports only 3.7+ now.
